name: Container Build image

on:
  push:
    branches:
      - '**'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry scorpio2002/docker-nexus
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: scorpio2002/docker-nexus
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        no_push: true
